name: nest-api

on:
  push:
    branches:
      - "im6h"
  pull_request:
    branches:
      - "im6h"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test

